# Generated by Django 4.2.6 on 2023-10-19 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('siteid', models.IntegerField()),
                ('filterwordsid', models.IntegerField()),
                ('tts_enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitename', models.CharField(max_length=128, unique=True)),
                ('internal_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Python_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='FilterWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('wordAlias', models.CharField(max_length=1022)),
                ('subwordalias', models.CharField(blank=True, max_length=255, null=True)),
                ('stopword', models.CharField(blank=True, max_length=255, null=True)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Python_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('insert_date', models.DateTimeField(auto_now_add=True)),
                ('article_date', models.DateTimeField()),
                ('autor', models.CharField(default='none', max_length=128)),
                ('url', models.URLField(max_length=1022)),
                ('article_name', models.TextField()),
                ('article_text', models.TextField()),
                ('visitors_count', models.IntegerField(default=0)),
                ('is_top_article', models.BooleanField(default=False)),
                ('screenshot_url', models.CharField(blank=True, max_length=90, null=True)),
                ('status', models.IntegerField(default=1)),
                ('found_word', models.CharField(blank=True, max_length=255, null=True)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Python_app.client')),
            ],
        ),
    ]
